```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

setwd(rprojroot::find_rstudio_root_file())

```

```{r eval=FALSE}
library(dplyr)
library(readr)
```

## GEE scripts {-}

Bring GEE scripts into the current rProject by cloning the GEE git and copying over the .js files.  

```{bash engine.opts='-l', eval=FALSE}
# set directory to clone GEE git into (should be empty)
cd 1_code/GEE

# delete all .js files in directory
rm *.js

# clone gee scripts
git clone https://earthengine.googlesource.com/users/bgcasey/climate_downscaling


# add the .js file extention to files
find climate_downscaling -type f -not -name "*.*" -exec mv "{}" "{}".js \;

# move .js files up a directory
mv -v climate_downscaling/*.js .

# move functions folder up a directory
mv -v climate_downscaling/functions/ .

# delete .git folder
rm -r climate_downscaling/
```


## GEE covariates .CSV {-}

```{r eval=FALSE}
gee_cov_all<-read_csv("0_data/manual/gee_tables/ibutton_all_indices.csv")
gee_cov_all$Project[gee_cov_all$Project== "WOOD"] <- "wood"
gee_cov_all$Project[gee_cov_all$Project== "HL"] <- "HILLS"
gee_cov_all<-rename(gee_cov_all, c("Site_StationKey" = "St_SttK", "Month"="month", "Year"= "year", "tree_coverfraction"="tree-coverfraction"))

### add latitude
load("0_data/manual/iButton_data/spatial/ss_xy.rData")

library(sf)

gee_cov_all<-dplyr::left_join(gee_cov_all, ss_xy, by = c("Project", "Site_StationKey"))%>%
  dplyr::select(-c(Long, min_year, max_year, geometry))

save(gee_cov_all, file="0_data/manual/gee_tables/gee_cov_all.rData")
```


### Join with response variable {-}

```{r eval=FALSE}
load("0_data/manual/iButton_data/iButton_cNA_diff.rData")

data_full<-left_join(iButton_cNA_diff, gee_cov_all, by=c("Project", "Site_StationKey", "Month", "Year"))%>%
  dplyr::select(-date)%>%
  as.data.frame()
```

### Add season column {-}

```{r eval=FALSE}

data_full<-data_full%>%
 mutate(season_4 = case_when(
      Month %in%  9:11 ~ "Fall",
      Month %in%  c(12, 1, 2)  ~ "Winter",
      Month %in%  3:5  ~ "Spring",
      TRUE ~ "Summer"))%>%
  mutate(season_2 = case_when(
      Month %in%  c(10:12, 1, 2,3) ~ "Winter",
      TRUE ~ "Summer"))

save(data_full, file="0_data/manual/formatted_for_models/data_full.rData")

write.csv(data_full, file="0_data/manual/formatted_for_models/data_full.csv", row.names = FALSE)  
```

## GEE rasters
```{r eval=FALSE}
library(raster)
library(terra)
library(dplyr)
library(foreach)
library(stringr)
```

### Import GEE rasters

### Mosaic rasters {-}

```{r eval=FALSE}

# Load study area
study_area<-st_read("../Data/Canada/alberta_bc")

# dataPath <- "/Volumes/GoogleDrive/My Drive/PhD/thesis/chapter_1/empirical/0_data/external/CL_LiDAR/grid_metrics_surfaces/"
bl<-list.dirs(path="0_data/external/GEE_rasters/", full.names = T, recursive = T)

#set temp directory to an external drive to free up harddrive space
rasterOptions(tmpdir=file.path("../r_tmp")) 

foreach (j = 1:length(bl)) %do%
{
  t1 = proc.time()
  print(paste("---- Begin",bl[j], Sys.time()))
  fl <- list.files(path=paste0("0_data/external/GEE_rasters/", bl[j]), pattern = '*.tif$', recursive = T, full.names = T)
  print(paste("----",bl[j]," file scan complete", Sys.time()))
  fl <- lapply(fl, brick)
  print(paste("----",bl[j]," lapply raster::brick  complete", Sys.time()))
  fl$fun <- mean
  fl$tolerance <-.5
  x <- do.call(raster::mosaic, fl)
  names(x)<-names(fl[[]])
  print(paste("----",bl[j]," mosaic complete!", Sys.time()))
  x<-raster::crop(x, study_area) # preserve band names when savinbg by converting the stack to a rast object from the terra package.
  print(paste("----",bl[j]," crop complete", Sys.time()))
  x<-terra::rast(x)
  writeRaster(x, filename=paste0("0_data/manual/raster_mosaics/",bl[j]), format="GTiff",  overwrite=T)
  print(paste("----",bl[j]," saved as GeoTIFF", Sys.time()))
  print("process time")
  print(proc.time() - t1)
  removeTmpFiles(0) #The raster package can store a lot of files. This removes any temp raster files generated   during the loop
}
```




``` {r }
x2<-crop(x, ab_bc)
fixed2<-crop(fixed, ab_bc)

st<-stack(x, fixed)




# preserve band names when savinbg by converting the stack to a rast object from the terra package.
x1<-terra::rast(x)


writeRaster(x1, filename="0_data/manual/raster_mosaics/time_series_06_2b.tif",  overwrite=T)

time_series_06_2b<-raster("0_data/manual/raster_mosaics/time_series_06_2b.tif")

st<-stack(time_series_06_2b, fixed2)



#####
fix_names<-brick("0_data/external/GEE_rasters//fixed/neighborhood_all_fixed_4s-0000062720-0000062720.tif")   
names(fix_names)

fixed_3<-fixed #names(fixed)
names(fixed_3)<-gsub("_mean", "",names(fix_names))

fixed_4<-raster::crop(fixed_3, study_area)

#test cropped extent
extent(study_area)
extent(fixed_4)
extent(ts_summer)

test_combined<-brick(fixed_4, ts_summer)

# if works
fixed_AB_BC<-terra::rast(fixed_4)
writeRaster(fixed_AB_BC, filename='0_data/manual/raster_mosaics/fixed_AB_BC.tif', format="GTiff", overwrite=TRUE)

```

### Crop raster mosaics {-}

```{r}
study_area<-st_read("../Data/Canada/alberta_bc")

# raster mosaic of fixed spatial variables
fixed<-raster::brick("0_data/manual/raster_mosaics/fixed.tif")%>%
  crop(study_area)
writeRaster(fixed, filename='0_data/manual/raster_mosaics/fixed_AB_BC.tif', format="GTiff", overwrite=TRUE)


ts_summer<-x2

test<-stack(x2, ts_summer)

# raster mosaic of time series variables
# summer
ts_summer<-raster::brick("0_data/manual/raster_mosaics/time_series_06.tif")%>%
  crop(ab_bc)
writeRaster(ts_summer, filename="0_data/manual/raster_mosaics/time_series_06_AB_BC.tif", format="GTiff", overwrite=TRUE)

```



### Combine raster mosaics {-}

```{r eval=FALSE}
ts_summer_AB_BC<-raster::brick("0_data/manual/raster_mosaics/time_series_06_AB_BC.tif")
fixed_AB_BC<-raster::brick("0_data/manual/raster_mosaics/fixed_AB_BC.tif")

gee_all_summer<-brick(fixed_AB_BC, ts_summer_AB_BC)
writeRaster(gee_all_summer, filename="0_data/manual/raster_mosaics/gee_all_summer.tif", format="GTiff", overwrite=TRUE)
```


