
```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r eval=FALSE}
library(dplyr)
library(readr)
```


### Import GEE covariates {-}

```{r eval=FALSE}
# tbl <-list.files(path="0_data/manual/gee_tables/", pattern = "*.csv", full.names = TRUE) 

landCover<-read_csv("0_data/manual/gee_tables/ibutton_landCover.csv", col_types=c("forest_type"="factor", "discrete_classification"="factor"))%>%
  rename("tree_coverfraction"="tree-coverfraction")
TWI<-read_csv("0_data/manual/gee_tables/ibutton_TWI.csv")
terrain<-read_csv("0_data/manual/gee_tables/ibutton_terrain.csv")
sentinel<-read_csv("0_data/manual/gee_tables/ibutton_sentinel_neighborhood_indices.csv")
snow<-read_csv("0_data/manual/gee_tables/ibutton_snow_indices.csv")


# join into a single covariate data frame
gee_cov_all<-sentinel%>%
  full_join(TWI)%>%
  full_join(terrain)%>%
  full_join(landCover)%>%
  full_join(snow)%>%
  rename(c(Month=month, Year=year, Site_StationKey=St_SttK))

save(gee_cov_all, file="0_data/manual/gee_tables/gee_cov_all.rData")

write_csv(gee_cov_all, file="0_data/manual/gee_tables/gee_cov_all.csv")     
```

### Join with response variable {-}

```{r eval=FALSE}
load("0_data/manual/iButton_data/iButton_cNA_diff.rData")

model_df<-left_join(iButton_cNA_diff, gee_cov_all, by=c("Project", "Site_StationKey", "Month", "Year"))%>%
  dplyr::select(Project, Site_StationKey, Month, Year, Tmax_Month:tree_coverfraction, -date)

save(model_df, file="0_data/manual/for_models/model_df.rData")
```














