

``` {r eval=FALSE}
library(lme4)
library(lmerTest)
library(corr)


load("0_data/manual/for_models/data_full.rData")

```

### Checl for multicollinearity between predictors {-}


```{r}
pairs_cov <-data_full[c(14:40, 43)]

#visualize with corrplot. Easier to visualize with a lot of variables
M<-cor(pairs_cov, method = "pearson", use="pairwise.complete.obs")
corrplot(M, tl.cex=0.5, method="number", type ="upper", addCoefasPercent=TRUE, order = "hclust", number.cex=.5, cl.cex=.5
)
```
### Univariate models {-}


```{r}

data<-data_full%>%na.omit()

pred<-as.data.frame(colnames(data_full[c(14:45)]))%>%
  rename("Pred"="colnames(data_full[c(14:45)])")

#  [1] "NDVI"                      "EVI"                      
#  [3] "NDMI"                      "SAVI"                     
#  [5] "BSI"                       "SI"                       
#  [7] "LAI"                       "TWI"                      
#  [9] "hnd"                       "elevation"                
# [11] "slope"                     "aspect"                   
# [13] "HLI"                       "TPI"                      
# [15] "northness"                 "snow"                     
# [17] "NDSI"                      "pr"                       
# [19] "srad"                      "vs"                       
# [21] "canopy_height"             "canopy_standard_deviation"
# [23] "ERA5_temp_max"             "ERA5_temp_min"            
# [25] "ERA5_temp_mean"            "ERA5_wind_speed"          
# [27] "cloud_fraction"            "cloud_probability"        
# [29] "discrete_classification"   "forest_type"              
# [31] "tree_coverfraction"        "Lat"   

allModelsList <- lapply(paste("Tavg_diff ~", pred), as.formula)
allModelsResults <- lapply(allModelsList, function(x) lm(x, data = data)) 
allModelsSummaries = lapply(allModelsResults, summary) 




```



### Evaluate random effects {-}

```{r eval=FALSE}
m0<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey), data=data_full)
m1<-lmer(Tmax_diff ~ 1 + (1|Month/Site_StationKey), data=data_full)
m2<-lmer(Tmax_diff ~ 1 + (1|Month), data=data_full)
m3<-lmer(Tmax_diff ~ 1 + (1|Year/Site_StationKey), data=data_full)
m4<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey/Month), data=data_full)
m5<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey/season_2), data=data_full)
m6<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey)+(1|season_2), data=data_full)
m7<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey/season_4), data=data_full)
m8<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey)+(1|season_4), data=data_full)
m9<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey)+(1|Month), data=data_full)

anova(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9)

anova(m4, m9)

# m4c
```


```{r}
m<-lmer(Tavg_diff ~ 
        NDVI+
        EVI+
        NDMI+
        SAVI+
        BSI+
        SI+
        logTWI+
        TWI+
        elevation+
        slope+
        aspect+
        HLI+
        TPI+
        NDSI+
        srad+
        vs+
        canopy_height+
        canopy_standard_deviation+
        cloud_fraction+
        cloud_probability+
        ERA5_temp_mean+
        tree_coverfraction+
        (1|Site_StationKey/Month), data=data_full)
summary(m)

m_cov<-as.data.frame(as.matrix(vcov(m)))%>%mutate_if(is.numeric, round, digits=3)
m_vif<-as.data.frame(vif(m))


m1<-lmer(Tavg_diff ~ 
        NDVI+
        NDMI+
        BSI+
        SI+
        logTWI+
        TWI+
        elevation+
        slope+
        aspect+
        HLI+
        TPI+
        NDSI+
        srad+
        vs+
        canopy_height+
        canopy_standard_deviation+
        cloud_fraction+
        cloud_probability+
        ERA5_temp_mean+
        (1|Site_StationKey/Month), data=data_full)
summary(m1)

m_cov<-as.data.frame(as.matrix(vcov(m1)))%>%mutate_if(is.numeric, round, digits=3)
m_vif<-as.data.frame(vif(m1))



m2<-lmer(Tavg_diff ~ 
        NDVI+
        NDMI+
        SI+
        logTWI+
        TWI+
        elevation+
        slope+
        aspect+
        HLI+
        TPI+
        NDSI+
        srad+
        vs+
        canopy_height+
        canopy_standard_deviation+
        cloud_probability+
        ERA5_temp_mean+
        (1|Site_StationKey/Month), data=data_full)
summary(m2)

m_cov<-as.data.frame(as.matrix(vcov(m2)))%>%mutate_if(is.numeric, round, digits=3)
m_vif<-as.data.frame(vif(m2))


m3<-lmer(Tavg_diff ~ 
        NDVI+
        NDMI+
        SI+
        logTWI+
        elevation+
        slope+
        HLI+
        TPI+
        NDSI+
        srad+
        vs+
        canopy_height+
        canopy_standard_deviation+
        cloud_probability+
        ERA5_temp_mean+
        (1|Site_StationKey/Month), data=data_full)
summary(m3)

m_cov<-as.data.frame(as.matrix(vcov(m3)))%>%mutate_if(is.numeric, round, digits=3)
m_vif<-as.data.frame(vif(m3))


m4<-lmer(Tavg_diff ~ 
        NDVI+
        SI+
        logTWI+
        elevation+
        slope+
        pr+
        HLI+
        TPI+
        NDSI+
        srad+
        vs+
        canopy_height+
        cloud_probability+
        ERA5_temp_mean+
        (1|Site_StationKey/Month), data=data_full)
summary(m4)

m_cov<-as.data.frame(as.matrix(vcov(m4)))%>%mutate_if(is.numeric, round, digits=3)
m_vif<-as.data.frame(vif(m4))
```


```{r eval=FALSE}
load("0_data/manual/for_models/data_full.rData")

test_df<-filter(model_df, Tmax_diff>-5)%>%
  drop_na()



## random effects



m1<-lmer(Tmax_diff ~ 
           scale(NDVI_mean) +              
scale(NDMI_mean) +               
scale(EVI_mean) +               
scale(SAVI_mean) +               
scale(BSI_mean) +               
scale(SI_mean) +                 
scale(LAI_mean) +               
#scale(logTWI) +                  
scale(TWI) +                    
scale(elevation) +               
scale(slope) +                  
scale(aspect) +                  
scale(HLI) +                    
scale(tpi) +         
           + (1|Site_StationKey), data=test_df, na.action=na.fail)

d_m<-d_in_1<-MuMIn::dredge(m1, extra = c(r2=function(x) round(r.squaredGLMM(x)[1,c(1,2)],3)))

## try month as a random effect
m4<-lmer(Tmax_diff ~ 
           scale(NDVI_mean) +              
scale(NDMI_mean) +               
scale(EVI_mean) +               
scale(SAVI_mean) +               
           
scale(SI_mean) +                 
               
#scale(logTWI) +                  
scale(TWI) +                    
         
                
                  
scale(HLI) +                    
        
           + (1|Month/Site_StationKey), data=test_df, na.action=na.fail)




m2<-lmer(Tmax_diff ~ scaleTWI + (1|Site_StationKey), data=test_df)
m3<-lmer(Tmax_diff ~ LAI + (1|Site_StationKey), data=test_df)
m0<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey), data=test_df)

m1<-lm(Tmax_diff ~ HLI, data=test_df)

summary(m1)
anova(m0, m1)


ggplot(test_df, aes(x = HLI, y = Tmax_diff)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")


```

#### Evaluate random effects {-}

```{r eval=FALSE}
# get seasons
test_df<-model_df %>%
  mutate(
    season = case_when(
      Month %in%  9:11 ~ "Fall",
      Month %in%  c(12, 1, 2)  ~ "Winter",
      Month %in%  3:5  ~ "Spring",
      TRUE ~ "Summer"))


w1<-lm(Tavg_diff ~ vs, data = data_full)
w2<-lm(Tavg_diff ~ ERA5_wind_speed, data = data_full)
w3<-lm(Tavg_diff ~ TWI, data = data_full)
w4<-lm(Tavg_diff ~ hnd, data = data_full)
w5<-lm(Tavg_diff ~ cloud_probability, data = data_full)
w6<-lm(Tavg_diff ~ cloud_fraction, data = data_full)
w7<-lm(Tavg_diff ~ canopy_height, data = data_full)
w8<-lm(Tavg_diff ~ tree_coverfraction, data = data_full)
w9<-lm(Tavg_diff ~ aspect, data = data_full)
w10<-lm(Tavg_diff ~ northness, data = data_full)
w11 <-lm(Tavg_diff ~ northness, data = data_full)



m0<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey), data=test_df)
m1<-lmer(Tmax_diff ~ 1 + (1|Month/Site_StationKey), data=test_df)
m2<-lmer(Tmax_diff ~ 1 + (1|Month), data=test_df)
m3<-lmer(Tmax_diff ~ 1 + (1|Year/Site_StationKey), data=test_df)
m4<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey/Month), data=test_df)
m5<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey/season), data=test_df)
m6<-lmer(Tmax_diff ~ 1 + (1|Site_StationKey)+(1|season), data=test_df)



m0a<-lmer(Tmax_diff ~ elevation + (1+ season_4|Site_StationKey), data=test_df)
m0b<-lmer(Tmax_diff ~ elevation + (1|Site_StationKey) + (season_4-1|Site_StationKey), 
     data=test_df)

m0<-glm(OCC ~ 1, data=d3, subset=SS_lidar_timelag==0, family = binomial, offset = OFF,  na.action = na.exclude)

m1<-lme4::glmer(OCC ~ 1 + (1|SS), data=d3, subset=SS_lidar_timelag==0, family = binomial, offset = OFF,  na.action = na.exclude)

m2<-lme4::glmer(OCC ~ 1 + (1|SS) + (1|ss_year), data=d3, subset=SS_lidar_timelag==0, family = binomial, offset = OFF,  na.action = na.exclude)

m3<-lme4::glmer(OCC ~ 1 + (1|ss_year/SS), data=d3, subset=SS_lidar_timelag==0, family = binomial, offset = OFF,  na.action = na.exclude)
```


## Explore effects by season

Make season specific plots to visualize

```{r eval=FALSE}

test_df<-filter(model_df, Tmax_diff>-5)%>%
  drop_na()

test_df<-test_df %>%
  mutate(
    season_4 = case_when(
      Month %in%  9:11 ~ "Fall",
      Month %in%  c(12, 1, 2)  ~ "Winter",
      Month %in%  3:5  ~ "Spring",
      TRUE ~ "Summer"))%>%
  mutate(  
  season_2 = case_when(
      Month %in%  c(10:12, 1, 2,3) ~ "Winter",
      TRUE ~ "Summer"))



ggplot(test_df, aes(y = Tmax_diff, x = NDVI_mean)) +
  geom_point() +
  xlab("NDVI") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_4)


ggplot(test_df, aes(y = Tmax_diff, x = HLI)) +
  geom_point() +
  xlab("HLI") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_4)


ggplot(test_df, aes(y = Tmax_diff, x = aspect)) +
  geom_point() +
  xlab("aspect") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_4)

ggplot(test_df, aes(y = Tmax_diff, x = tpi)) +
  geom_point() +
  xlab("tpi") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_2)



ggplot(test_df, aes(y = Tmax_diff, x = elevation)) +
  geom_point() +
  xlab("elevation") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_4)



ggplot(test_df, aes(y = Tmax_diff, x = snow)) +
  geom_point() +
  xlab("SI") +
  ylab("Tmax_diff)") +
  theme_classic(base_size = 15) +
  stat_smooth(method = "lm", formula = 'y ~ x', se=F,fullrange = T) +
  facet_wrap(~season_4)

```

